"""empty message

Revision ID: 2ca956711e26
Revises: 
Create Date: 2022-04-10 16:08:01.419720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca956711e26'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AddressBook',
    sa.Column('abook_id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('abook_id', name=op.f('pk_AddressBook'))
    )
    op.create_table('AddressBookEmail',
    sa.Column('abookemail_id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('abook_id', sa.Integer(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('abookemail_id', name=op.f('pk_AddressBookEmail'))
    )
    op.create_table('AddressBookFAX',
    sa.Column('abookfax_id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('abook_id', sa.Integer(), nullable=True),
    sa.Column('faxnumber', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=30), nullable=True),
    sa.Column('to_person', sa.String(length=150), nullable=True),
    sa.Column('to_location', sa.String(length=150), nullable=True),
    sa.Column('to_voicenumber', sa.String(length=150), nullable=True),
    sa.Column('faxcatid', sa.Integer(), nullable=True),
    sa.Column('faxfrom', sa.Integer(), nullable=True),
    sa.Column('faxto', sa.Integer(), nullable=True),
    sa.Column('printer', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('abookfax_id', name=op.f('pk_AddressBookFAX'))
    )
    op.create_table('BarcodeRoute',
    sa.Column('barcode_id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.Column('alias', sa.String(length=40), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('printer', sa.String(length=100), nullable=True),
    sa.Column('faxcatid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('barcode_id', name=op.f('pk_BarcodeRoute'))
    )
    op.create_table('CoverPages',
    sa.Column('cover_id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('cover_id', name=op.f('pk_CoverPages'))
    )
    op.create_table('DIDRoute',
    sa.Column('didr_id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('routecode', sa.String(length=10), nullable=False),
    sa.Column('alias', sa.String(length=40), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('printer', sa.String(length=100), nullable=True),
    sa.Column('faxcatid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('didr_id', name=op.f('pk_DIDRoute'))
    )
    op.create_table('DistroList',
    sa.Column('dl_id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('listname', sa.String(length=255), nullable=False),
    sa.Column('listdata', sa.Text(), nullable=True),
    sa.Column('lastmod_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('lastmod_user', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('dl_id', name=op.f('pk_DistroList'))
    )
    op.create_table('DynConf',
    sa.Column('dynconf_id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('device', sa.String(length=20), nullable=True),
    sa.Column('callid', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('dynconf_id', name=op.f('pk_DynConf'))
    )
    op.create_table('FaxArchive',
    sa.Column('fid', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('faxnumid', sa.Integer(), nullable=True),
    sa.Column('companyid', sa.Integer(), nullable=True),
    sa.Column('faxpath', sa.String(length=255), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('faxcatid', sa.Integer(), nullable=True),
    sa.Column('didr_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lastoperation', sa.TIMESTAMP(), nullable=True),
    sa.Column('lastmoduser', sa.Integer(), nullable=True),
    sa.Column('lastmoddate', sa.TIMESTAMP(), nullable=True),
    sa.Column('archstamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('modemdev', sa.String(length=10), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('origfaxnum', sa.String(length=20), nullable=True),
    sa.Column('faxcontent', sa.Text(), nullable=True),
    sa.Column('inbox', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('fid', name=op.f('pk_FaxArchive'))
    )
    op.create_table('FaxCategory',
    sa.Column('catid', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('catid', name=op.f('pk_FaxCategory'))
    )
    op.create_table('Modems',
    sa.Column('devid', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('device', sa.String(length=10), nullable=False),
    sa.Column('alias', sa.String(length=40), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('printer', sa.String(length=100), nullable=True),
    sa.Column('faxcatid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('devid', name=op.f('pk_Modems'))
    )
    op.create_table('SysLog',
    sa.Column('syslogid', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('logdate', sa.TIMESTAMP(), nullable=True),
    sa.Column('logtext', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('syslogid', name=op.f('pk_SysLog'))
    )
    op.create_table('UserAccount',
    sa.Column('uid', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=99), nullable=False),
    sa.Column('email_sig', sa.Text(), nullable=True),
    sa.Column('user_tsi', sa.String(length=100), nullable=True),
    sa.Column('from_company', sa.String(length=150), nullable=True),
    sa.Column('from_location', sa.String(length=150), nullable=True),
    sa.Column('from_voicenumber', sa.String(length=150), nullable=True),
    sa.Column('from_faxnumber', sa.String(length=150), nullable=True),
    sa.Column('coverpage_id', sa.Integer(), nullable=True),
    sa.Column('faxperpageinbox', sa.Integer(), nullable=True),
    sa.Column('faxperpagearchive', sa.Integer(), nullable=True),
    sa.Column('superuser', sa.BOOLEAN(), nullable=True),
    sa.Column('can_del', sa.BOOLEAN(), nullable=True),
    sa.Column('last_mod', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_ip', sa.String(length=15), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('modemdevs', sa.Text(), nullable=True),
    sa.Column('didrouting', sa.Text(), nullable=True),
    sa.Column('faxcats', sa.Text(), nullable=True),
    sa.Column('pwdexpire', sa.DATE(), nullable=True),
    sa.Column('pwdcycle', sa.Integer(), nullable=True),
    sa.Column('pwd_reuse', sa.BOOLEAN(), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('wasreset', sa.BOOLEAN(), nullable=True),
    sa.Column('acc_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('any_modem', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_UserAccount'))
    )
    op.create_table('UserPasswords',
    sa.Column('upid', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('pwdhash', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('upid', name=op.f('pk_UserPasswords'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserPasswords')
    op.drop_table('UserAccount')
    op.drop_table('SysLog')
    op.drop_table('Modems')
    op.drop_table('FaxCategory')
    op.drop_table('FaxArchive')
    op.drop_table('DynConf')
    op.drop_table('DistroList')
    op.drop_table('DIDRoute')
    op.drop_table('CoverPages')
    op.drop_table('BarcodeRoute')
    op.drop_table('AddressBookFAX')
    op.drop_table('AddressBookEmail')
    op.drop_table('AddressBook')
    # ### end Alembic commands ###
